// Bu blok HAR BIR skriptning boshida takrorlanadi (use_figma chaqiruvlari izolyatsiyalangan).
// Alohida yuborilmaydi — faqat hujjat sifatida shu yerda.
const HEX=h=>{const n=parseInt(h.slice(1),16);return{r:((n>>16)&255)/255,g:((n>>8)&255)/255,b:(n&255)/255}};
const F=(h,o)=>[Object.assign({type:'SOLID',color:HEX(h)},o===undefined?{}:{opacity:o})];
const K600='#1B4F9C',K500='#3A6DB6',K300='#8FB4E8',K200='#B9CFED',K100='#DCE7F6',K50='#EFF4FB',K800='#113363',K900='#0C2546',K950='#07172D';
const AMB='#E8862D',AMB200='#F5CC96',AMB900='#331B04';
const N0='#FFFFFF',N50='#F7F8FA',N100='#EFF1F5',N200='#E3E6EB',N300='#CDD2DA',N400='#A8AFBB',N500='#808896',N600='#5F6672',N700='#474D58',N800='#31363F',N900='#1F232A',N950='#121417';
const R600='#B3261E',R50='#FCEEED',R100='#F7D5D3',R800='#6E1713';
const G600='#2E7D32',G50='#ECF5ED',G200='#A9D2AC',G800='#1C4E1F';
const S500='#B07B00',S50='#FBF4E1',S200='#E9CC7C',S700='#6E4D00';
await Promise.all(['Regular','Medium','Semi Bold','Bold'].map(s=>figma.loadFontAsync({family:'Inter',style:s})));
function T(s,fs,st,h,o={}){const t=figma.createText();t.fontName={family:'Inter',style:st};t.characters=s;t.fontSize=fs;t.fills=F(h);if(o.lh)t.lineHeight={unit:'PIXELS',value:o.lh};if(o.ls)t.letterSpacing={unit:'PIXELS',value:o.ls};if(o.w){t.textAutoResize='HEIGHT';t.resize(o.w,10);}if(o.a)t.textAlignHorizontal=o.a;return t;}
function AL(dir,o={}){const f=figma.createAutoLayout(dir);Object.assign(f,o);return f;}
function pad(f,a,b,c,d){f.paddingTop=a;f.paddingRight=b??a;f.paddingBottom=c??a;f.paddingLeft=d??b??a;}
function fillH(n){n.layoutSizingHorizontal='FILL';}
function TW(p,s,fs,st,h,o={}){const t=T(s,fs,st,h,o);t.textAutoResize='HEIGHT';p.appendChild(t);t.layoutSizingHorizontal='FILL';return t;}
function spacer(p){const s=figma.createFrame();s.fills=[];p.appendChild(s);s.layoutSizingHorizontal='FILL';s.layoutSizingVertical='FILL';return s;}
function phone(name,x,y,bg){const p=AL('VERTICAL',{name});p.resize(390,844);p.fills=F(bg);p.cornerRadius=24;p.clipsContent=true;p.strokes=F('#C9CED6');p.strokeWeight=1;p.x=x;p.y=y;return p;}
function osbar(p,time,right,fg,mut){const r=AL('HORIZONTAL',{name:'OS bar',primaryAxisAlignItems:'SPACE_BETWEEN',counterAxisAlignItems:'CENTER'});p.appendChild(r);r.resize(390,44);fillH(r);pad(r,0,24,0,24);r.appendChild(T(time,13,'Semi Bold',fg));r.appendChild(T(right,11,'Semi Bold',mut,{ls:1.5}));return r;}
function btn(p,label,bg,fg,o={}){const b=AL('HORIZONTAL',{name:'Btn / '+label,primaryAxisAlignItems:'CENTER',counterAxisAlignItems:'CENTER'});b.fills=bg?F(bg):[];if(o.stroke){b.strokes=F(o.stroke);b.strokeWeight=1.5;}b.cornerRadius=o.r??14;p.appendChild(b);b.resize(350,o.h??60);fillH(b);b.appendChild(T(o.label??label,o.fs??18,o.st??'Semi Bold',fg));return b;}
function chip(txt,bg,fg,bd,o={}){const c=AL('HORIZONTAL',{name:'Chip / '+txt,counterAxisAlignItems:'CENTER',itemSpacing:6,cornerRadius:999});c.fills=F(bg);if(bd){c.strokes=F(bd);c.strokeWeight=1;}pad(c,o.py??5,o.px??11);c.appendChild(T(txt,o.fs??13,'Medium',fg));return c;}
function card(p,o={}){const c=AL('VERTICAL',{name:o.name||'Card',cornerRadius:o.r??14,itemSpacing:o.gap??8});c.fills=F(o.bg||N0);c.strokes=F(o.bd||N200);c.strokeWeight=1;pad(c,o.p??16,o.p??16,o.p??16,o.p??16);if(p){p.appendChild(c);fillH(c);}return c;}
async function mount(pageId,secPrefix,frameName){const page=await figma.getNodeByIdAsync(pageId);await figma.setCurrentPageAsync(page);let host=page;if(secPrefix){host=page.children.find(n=>n.type==='SECTION'&&n.name.startsWith(secPrefix))||page;}const old=host.children.find(n=>n.name===frameName);if(old)old.remove();return host;}
const MARK=s=>{const m=figma.createNodeFromSvg('<svg width="'+s+'" height="'+s+'" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="44" height="44" rx="12" fill="#1B4F9C"/><path d="M13 27 L22 15 L31 27" stroke="#FFFFFF" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="13" cy="31" r="3.5" fill="#E8862D"/></svg>');m.name='Logo mark';return m;};
function kbd(p){const g=AL('VERTICAL',{name:'Klaviatura',itemSpacing:7});g.fills=F('#D6D9DF');p.appendChild(g);fillH(g);pad(g,8,6,22,6);const rows=[['1','2','3'],['4','5','6'],['7','8','9'],['','0','⌫']];for(const r of rows){const row=AL('HORIZONTAL',{itemSpacing:7});g.appendChild(row);fillH(row);for(const k of r){const key=AL('HORIZONTAL',{primaryAxisAlignItems:'CENTER',counterAxisAlignItems:'CENTER',cornerRadius:8});key.fills=F(k===''||k==='⌫'?'#C4C8D0':N0);row.appendChild(key);key.resize(100,52);key.layoutSizingHorizontal='FILL';if(k)key.appendChild(T(k,k==='⌫'?16:22,'Medium',N900));}}return g;}
function pinpad(p,faded,helpLabel){const g=AL('VERTICAL',{name:'PinPad',itemSpacing:13,counterAxisAlignItems:'CENTER'});p.appendChild(g);fillH(g);g.paddingBottom=34;const rows=[['1','2','3'],['4','5','6'],['7','8','9'],[helpLabel||'','0','⌫']];for(const r of rows){const row=AL('HORIZONTAL',{itemSpacing:40});g.appendChild(row);for(const k of r){const isMut=k===''||k==='⌫'||(helpLabel&&k===helpLabel);const key=AL('HORIZONTAL',{primaryAxisAlignItems:'CENTER',counterAxisAlignItems:'CENTER',cornerRadius:16});key.resize(64,64);if(isMut){key.fills=[];}else{key.fills=F(faded?N100:N0);key.strokes=F(N200);key.strokeWeight=1;}row.appendChild(key);if(k)key.appendChild(T(k,isMut?(k==='⌫'?18:15):26,isMut?'Medium':'Semi Bold',isMut?(k==='⌫'?N500:K600):(faded?N400:N900)));}}return g;}
function dots(p,states){const d=AL('HORIZONTAL',{itemSpacing:18,name:'PIN dots'});p.appendChild(d);for(const s of states){const e=figma.createEllipse();e.resize(16,16);if(s==='on'){e.fills=F(K600);}else{e.fills=[];e.strokes=F(s==='err'?R600:N400);e.strokeWeight=2.5;}d.appendChild(e);}return d;}
function codeBoxes(p,chars,state){const r=AL('HORIZONTAL',{itemSpacing:9,name:'CodeBoxes'});p.appendChild(r);fillH(r);for(let i=0;i<6;i++){const b=AL('HORIZONTAL',{primaryAxisAlignItems:'CENTER',counterAxisAlignItems:'CENTER',cornerRadius:12});b.fills=F(state==='err'?R50:N0);const focus=state==='focus'&&i===chars.length;b.strokes=F(state==='err'?R600:(focus?K500:N400));b.strokeWeight=(state==='err'||focus)?2:1.5;b.resize(52,64);r.appendChild(b);b.layoutSizingHorizontal='FILL';if(chars[i])b.appendChild(T(chars[i],28,'Bold',N900));}return r;}
function avatar(p,initials,bg,fg,size){const a=AL('HORIZONTAL',{primaryAxisAlignItems:'CENTER',counterAxisAlignItems:'CENTER',cornerRadius:999,name:'Avatar'});a.fills=F(bg);a.resize(size,size);if(p)p.appendChild(a);a.appendChild(T(initials,Math.round(size*0.34),'Bold',fg));return a;}
function divider(p){const d=figma.createFrame();d.fills=F(N200);p.appendChild(d);d.resize(100,1);d.layoutSizingHorizontal='FILL';return d;}
